# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  windows_bsdtar:
    runs-on: windows-latest

    steps:
    - name: Create multiple files
      run: |
        $ErrorActionPreference = 'SilentlyContinue'
        echo "Create random files"
        mkdir windows_tmp
        mkdir cache
        git clone https://github.com/telescopejs/telescope.git
        #for($i = 1 ; $i -le 2000 ; $i++) { dd if=/dev/urandom bs=1048576 count=1 of=cache/file$i }
        
    - uses: actions/setup-node@v3
      with:
        node-version: 12.x
        
    - run: |
        cd telescope
        npm install
        du -sh node_modules
        cp -r node_modules/ ../cache/tmp1/
        cp -r node_modules/ ../cache/tmp2/
        cp -r node_modules/ ../cache/tmp3/
        cp -r node_modules/ ../cache/tmp4/
        du -sh ../cache
        
    - name: Test with tar only
      run: |
        $ErrorActionPreference = 'SilentlyContinue'
        zstd -V
        tar --version
        echo "Running tar standalone compression then decompression"
        (Measure-Command { tar -cf file.tar cache | Out-Default }).ToString()
        ls file.tar
        (Measure-Command { tar -xf file.tar -C windows_tmp | Out-Default }).ToString()
        rm file.tar
        rm -r windows_tmp/*
    
    - name: Test with tar then zstd
      run: |
        echo "Running tar + zstd in two steps compression then decompression"
        (Measure-Command { tar -cf file_combined.tar cache | Out-Default }).ToString()
        (Measure-Command { zstd -o file_combined.tzst file_combined.tar | Out-Default }).ToString()
        rm file_combined.tar
        ls file_combined.tzst
        (Measure-Command { zstd -d -o file_combined.tar file_combined.tzst | Out-Default }).ToString()
        (Measure-Command { tar -xf file_combined.tar -C windows_tmp | Out-Default }).ToString()
        rm file_combined.tzst
        rm -r windows_tmp/*
        
    - name: Test with tar then zstd to compress and bsdtar with zstd to decompress
      run: |
        echo "Running tar + zstd in two steps compression then decompression"
        (Measure-Command { tar -cf file_combined.tar cache | Out-Default }).ToString()
        (Measure-Command { zstd -o file_combined.tzst file_combined.tar | Out-Default }).ToString()
        rm file_combined.tar
        ls file_combined.tzst
        #(Measure-Command { tar --use-compress-program "zstd -d" -xf file_combined.tzst -C windows_tmp | Out-Default }).ToString()
        rm file_combined.tzst
        rm -r windows_tmp/*
        
    - if: ${{ runner.os == 'Windows' }}
      name: Use GNU tar
      shell: cmd
      run: |
        echo "Adding GNU tar to PATH"
        echo C:\Program Files\Git\usr\bin>>"%GITHUB_PATH%"

    - name: Test with tar then zstd for compression then decompress using gnutar with zstd
      run: |
        zstd -V
        tar --version
        echo "Running tar + zstd in two steps compression then decompression"
        (Measure-Command { tar -cf file_combined_gnu.tar cache | Out-Default }).ToString()
        (Measure-Command { zstd -o file_combined_gnu.tzst file_combined_gnu.tar | Out-Default }).ToString()
        rm file_combined_gnu.tar
        ls file_combined_gnu.tzst
        (Measure-Command { tar --use-compress-program "zstd -d" -xf file_combined_gnu.tzst -C windows_tmp | Out-Default }).ToString()
        rm file_combined_gnu.tzst 
        rm -r windows_tmp/*

    - name: Test with tar with zstd
      run: |
        echo "Running tar + zstd using --use-compress-program compression then decompression"
        #(Measure-Command { tar --use-compress-program zstd -cf file.tzst -P cache | Out-Default }).ToString()
        #ls file.tzst
        echo "Done"
  
  windows_gnutar:
    runs-on: windows-latest

    steps:
    - name: Create multiple files
      run: |
        $ErrorActionPreference = 'SilentlyContinue'
        echo "Create random files"
        mkdir windows_tmp
        mkdir cache
        for($i = 1 ; $i -le 2000 ; $i++) { dd if=/dev/urandom bs=1048576 count=1 of=cache/file$i }

    - if: ${{ runner.os == 'Windows' }}
      name: Use GNU tar
      shell: cmd
      run: |
        echo "Adding GNU tar to PATH"
        echo C:\Program Files\Git\usr\bin>>"%GITHUB_PATH%"

    - name: Test with tar only
      run: |
        zstd -V
        tar --version
        $ErrorActionPreference = 'SilentlyContinue'
        echo "Running tar standalone compression then decompression"
        (Measure-Command { tar -cf file_gnu.tar cache | Out-Default }).ToString()
        ls file_gnu.tar
        (Measure-Command { tar -xf file_gnu.tar -C windows_tmp | Out-Default }).ToString()
        rm file_gnu.tar
        rm -r windows_tmp/*
    
    - name: Test with tar then zstd
      run: |
        echo "Running tar + zstd in two steps compression then decompression"
        (Measure-Command { tar -cf file_combined_gnu.tar cache | Out-Default }).ToString()
        (Measure-Command { zstd -o file_combined_gnu.tzst file_combined_gnu.tar | Out-Default }).ToString()
        rm file_combined_gnu.tar
        ls file_combined_gnu.tzst
        (Measure-Command { zstd -d -o file_combined_gnu.tar file_combined_gnu.tzst | Out-Default }).ToString()
        (Measure-Command { tar -xf file_combined_gnu.tar -C windows_tmp | Out-Default }).ToString()
        rm file_combined_gnu.tzst
        rm -r windows_tmp/*
        
    - name: Test with tar with zstd
      run: |
        echo "Running tar + zstd using --use-compress-program compression then decompression"
        (Measure-Command { tar --use-compress-program zstd -cf file_gnu.tzst -P cache | Out-Default }).ToString()
        ls file_gnu.tzst
        (Measure-Command { tar --use-compress-program "zstd -d" -xf file_gnu.tzst -C windows_tmp | Out-Default }).ToString()
        rm file_gnu.tzst 
        rm -r windows_tmp/*
        echo "Done"
    
    - name: Test with tar then zstd for compression then decompress using tar with zstd
      run: |
        echo "Running tar + zstd in two steps compression then decompression"
        (Measure-Command { tar -cf file_combined_gnu.tar cache | Out-Default }).ToString()
        (Measure-Command { zstd -o file_combined_gnu.tzst file_combined_gnu.tar | Out-Default }).ToString()
        rm file_combined_gnu.tar
        ls file_combined_gnu.tzst
        (Measure-Command { tar --use-compress-program "zstd -d" -xf file_combined_gnu.tzst -C windows_tmp | Out-Default }).ToString()
        rm file_combined_gnu.tzst 
        rm -r windows_tmp/*
  
  linux_tar:
    runs-on: ubuntu-latest

    steps:
    - name: Create multiple files
      run: |
        echo "Create random files"
        mkdir cache linux_tmp
        for i in {1..2000}; do  dd if=/dev/urandom bs=1048576 count=1 of=cache/file$i; done

    - name: Test with tar only
      run: |
        zstd -V
        tar --version
        echo "Running tar standalone compression then decompression"
        time tar -cf file_gnu.tar cache
        ls file_gnu.tar
        time tar -xf file_gnu.tar -C linux_tmp
        rm -r file_gnu.tar linux_tmp/*
    
    - name: Test with tar then zstd
      run: |
        echo "Running tar + zstd in two steps compression then decompression"
        time tar -cf file_combined_gnu.tar cache
        time zstd -o file_combined_gnu.tzst file_combined_gnu.tar
        rm file_combined_gnu.tar
        ls file_combined_gnu.tzst
        time zstd -d -o file_combined_gnu.tar file_combined_gnu.tzst
        time tar -xf file_combined_gnu.tar -C linux_tmp
        rm -r file_combined_gnu.tzst linux_tmp/*
        
    - name: Test with tar with zstd
      run: |
        echo "Running tar + zstd using --use-compress-program compression then decompression"
        time tar --use-compress-program zstd -cf file_gnu.tzst -P cache
        ls file_gnu.tzst
        time tar --use-compress-program "zstd -d" -xf file_gnu.tzst -C linux_tmp
        rm -r file_gnu.tzst linux_tmp/*
        echo "Done"

    - name: Test with tar then zstd for compression then decompress using tar with zstd
      run: |
        echo "Running tar + zstd in two steps compression then decompression"
        time tar -cf file_combined_gnu.tar cache
        time zstd -o file_combined_gnu.tzst file_combined_gnu.tar
        rm file_combined_gnu.tar
        ls file_combined_gnu.tzst
        time tar --use-compress-program "zstd -d" -xf file_combined_gnu.tzst -C linux_tmp
        rm -r file_combined_gnu.tzst linux_tmp/*
        echo "Done"
