# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    - name: Create multiple files
      run: |
        $ErrorActionPreference = 'SilentlyContinue'
        echo "Create random files"
        mkdir cache
        for i in {1..200}; do dd if=/dev/urandom bs=1048576 count=1 of=cache/file$i; done
    
    - name: Test with zstd only
      run: |
        $ErrorActionPreference = 'SilentlyContinue'
        zstd.exe -V
        tar.exe --version
        echo "Running zstd standalone"
        (Measure-Command { zstd.exe -o file.zstd cache | Out-Default }).ToString()
        ls file.zstd
        
    - name: Test with tar only
      run: |
        $ErrorActionPreference = 'SilentlyContinue'
        echo "Running tar standalone"
        (Measure-Command { tar -cf file.tar cache | Out-Default }).ToString()
        #tar -cf file.tar file.txt
        ls file.tar
    
    - name: Test with tar then zstd
      run: |
        echo "Running tar + zstd in two steps"
        (Measure-Command { zstd.exe -o file_combined.zstd cache | Out-Default }).ToString()
        (Measure-Command { tar -cf file_combined.tzst file_combined.zstd | Out-Default }).ToString()
        ls file_combined.tzst
        
    - name: Test with tar with zstd
      run: |
        echo "Running tar + zstd using --use-compress-program"
        (Measure-Command { tar.exe --use-compress-program "zstd" -cf file.tzst -P cache | Out-Default }).ToString()
        #tar.exe --use-compress-program "zstd -T0" -cf file.tzst file.txt
        #tar.exe -I zstd -cf file.tzst file.txt
        ls file.tzst
        echo "Done"
