# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Test zstd
      run: |
        zstd.exe -V
        C:\windows\System32\tar.exe --version
        echo "Create random file"
        dd if=/dev/urandom of=file.txt count=150 bs=1048576
        #echo "Running zstd"
        #zstd.exe file.txt
        #echo "Running tar"
        #C:\windows\System32\tar.exe --use-compress-program "zstd -T0" -cf cache.tzst -P -C cache-dir --files-from manifest.txt
        #tar.exe --use-compress-program "zstd -T0" -czf cache.tgz file.txt
        #tar.exe --use-compress-program "./zstd-v1.4.4-win64/zstd.exe" -czf cache.tgz file.txt
        #tar.exe -czf cache.tgz file.txt
        C:\windows\System32\tar.exe -c file.txt | zstd.exe -T0 -o cache.tzst
        echo "Done"
        ls
