name: Fallback
on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  cross-os:
    runs-on: windows-latest 
    steps:
      - name: Cache using gnutar + zstd
        uses: pdotl/cache@main
        id: pdotl-cache
        with:
          path: cache-folder
          key: gnutar-zstd-key

      - name: Cache using bsdtar + gzip
        uses: actions/cache@v3
        id: actions-cache
        with:
          path: cache-folder
          key: bsdtar-gzip-key

      - name: Generate a file
        run: |
          mkdir -p cache-folder
          cd cache-folder
          if [ ! -f "1GB.bin" ]; then
            dd if=/dev/urandom of=1GB.bin count=1000 bs=1048576
          fi
          cat 1GB.bin | openssl dgst -sha256 > sha256.txt
        shell: bash
        if: steps.pdotl-cache.outputs.cache-hit != 'true' && steps.actions-cache.outputs.cache-hit != 'true'