name: Fallback
on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  cross-os:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest", "macos-latest" ]
    steps:
      - uses: pdotl/cache@main
        with:
          path: cache-folder
          key: ${{ runner.os }}-large-key

      - name: Generate a file
        run: |
          mkdir -p cache-folder
          cd cache-folder
          if [ ! -f "1GB.bin" ]; then
            dd if=/dev/urandom of=1GB.bin count=1000 bs=1048576
          fi
          cat 1GB.bin | openssl dgst -sha256 > sha256.txt
        shell: bash