# This is a basic workflow to help you get started with Actions

name: windows perf

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  windows-cache-creation:
    runs-on: windows-latest

    steps:
    - name: Create multiple files
      run: |
        $ErrorActionPreference = 'SilentlyContinue'
        echo "Create random files"
        mkdir windows_tmp
        mkdir cache
        git clone https://github.com/telescopejs/telescope.git
        for($i = 1 ; $i -le 100 ; $i++) { dd if=/dev/urandom bs=1048576 count=1 of=cache/file$i }
        
    - uses: actions/setup-node@v3
      with:
        node-version: 12.x
        
    - run: |
        cd telescope
        #npm install
        du -sh node_modules
        #cp -r node_modules/ ../cache/tmp1/
        #cp -r node_modules/ ../cache/tmp2/
        #cp -r node_modules/ ../cache/tmp3/
        #cp -r node_modules/ ../cache/tmp4/
        du -sh ../cache

    - name: BSDtar caching
      uses: actions/cache@v3
      with:
        path: cache
        key: ${{ runner.os }}-4
        
    - if: ${{ runner.os == 'Windows' }}
      name: Use GNU tar
      shell: cmd
      run: |
        echo "Adding GNU tar to PATH"
        echo C:\Program Files\Git\usr\bin>>"%GITHUB_PATH%"
        
    - name: GNUtar caching
      uses: actions/cache@v3
      with:
        path: cache
        key: ${{ runner.os }}-GNU-4
        
  windows-cache-restoration:
    runs-on: windows-latest
    needs: windows-cache-creation

    steps:
    
    - name: BSdtar caching
      uses: actions/cache@v3
      with:
        path: cache
        key: ${{ runner.os }}-4
        
    - run: |
        du -sh cache
        rm cache
    
    - if: ${{ runner.os == 'Windows' }}
      name: Use GNU tar
      shell: cmd
      run: |
        echo "Adding GNU tar to PATH"
        echo C:\Program Files\Git\usr\bin>>"%GITHUB_PATH%"
        
    - name: GNUtar caching
      uses: actions/cache@v3
      with:
        path: cache
        key: ${{ runner.os }}-GNU-4
        
    - run: |
        du -sh cache
        rm cache
